### PR TITLE
Log exception messages in several locations

### LINKED ISSUE #3213: Should log exception message in several locations
There are a number of places that catch exceptions and don't log the exception message (`.what()`). Consider adding the exception info at these locations:

```
src/ripple/basics/impl/make_SSLContext.cpp|348 col 9| catch (std::exception const&)
src/ripple/app/misc/impl/Manifest.cpp|151 col 5| catch (std::exception const&)
src/ripple/app/misc/impl/Manifest.cpp|282 col 5| catch (std::exception const&)
src/ripple/app/misc/impl/ValidatorSite.cpp|340 col 5| catch (std::exception &)
src/ripple/app/misc/NetworkOPs.cpp|892 col 5| catch (std::exception const&)
src/ripple/app/consensus/RCLConsensus.cpp|579 col 17| catch (std::exception const&)
src/ripple/app/ledger/impl/TransactionAcquire.cpp|239 col 5| catch (std::exception const&)
src/ripple/app/ledger/impl/LedgerMaster.cpp|746 col 13| catch (std::exception const&)
src/ripple/app/ledger/impl/LedgerMaster.cpp|1098 col 5| catch (std::exception const&)
src/ripple/app/ledger/impl/LedgerMaster.cpp|1227 col 5| catch (std::exception const&)
src/ripple/app/ledger/impl/LedgerMaster.cpp|1798 col 13| catch (std::exception const&)
src/ripple/app/ledger/impl/LedgerMaster.cpp|2093 col 5| catch (std::exception const&)
src/ripple/app/ledger/impl/OpenLedger.cpp|237 col 9| catch(std::exception const&)
src/ripple/app/ledger/Ledger.cpp|841 col 5| catch (std::exception const&)
src/ripple/app/ledger/OpenLedger.h|230 col 9| catch(std::exception const&)
src/ripple/app/ledger/ConsensusTransSetSF.cpp|69 col 9| catch (std::exception const&)
src/ripple/app/tx/impl/apply.cpp|152 col 5| catch (std::exception const&)
src/ripple/shamap/impl/SHAMap.cpp|159 col 13| catch (std::exception const&)
src/ripple/protocol/impl/STValidation.cpp|116 col 5| catch (std::exception const&)
src/ripple/rpc/handlers/PayChanClaim.cpp|83 col 5| catch (std::exception&)
src/ripple/overlay/impl/PeerImp.cpp|1520 col 5| catch (std::exception const&)
src/ripple/overlay/impl/PeerImp.cpp|2307 col 5| catch (std::exception const&)
src/ripple/overlay/impl/PeerImp.cpp|2381 col 5| catch (std::exception const&)
```

The following locations either don't log at all or need a closer review to decide if the exception message would be useful:

```
src/ripple/app/consensus/RCLConsensus.cpp|467 col 9| catch (std::exception const&)
src/ripple/app/ledger/impl/BuildLedger.cpp|142 col 13| catch (std::exception const&)
src/ripple/app/ledger/OrderBookDB.cpp|297 col 13| catch (std::exception const&)
src/ripple/app/paths/Pathfinder.cpp|438 col 5| catch (std::exception const&)
src/ripple/app/ledger/impl/LedgerToJson.cpp|176 col 5| catch (std::exception const&)
src/ripple/app/ledger/impl/InboundLedgers.cpp|285 col 9| catch (std::exception const&)
src/ripple/protocol/impl/STTx.cpp|199 col 5| catch (std::exception const&)
```

### PR DESCRIPTION
**Pull request by drlongle**
## High Level Overview of Change

This PR resolves #3213 and logs exception messages at several locations.

### Context of Change

At several locations in the code base, we catch an exception but do not log the exception messages. This PR adds code that logs the exception messages. This can be useful for analysis or debugging. The additional logging can have a (small) negative performance impact.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by intelliot** [comment]
This is `Testable` because we can try to trigger some of the exceptions and confirm that they are logged as expected

File: src/ripple/app/ledger/Ledger.h [hunk 1]
```diff
@@ -408,6 +408,7 @@ class Ledger final : public std::enable_shared_from_this<Ledger>,
     Fees fees_;
     Rules rules_;
     LedgerInfo info_;
+    beast::Journal j_ = beast::Journal(beast::Journal::getNullSink());
```
Comment (mtrippled) [inline src/ripple/app/ledger/Ledger.h:411]: I think it's safe to leave this unassigned in the class definition. It then gets assigned in the constructor.

File: src/ripple/app/ledger/impl/LedgerToJson.cpp [hunk 2]
```diff
@@ -192,9 +192,14 @@ fillJsonTx(Object& json, LedgerFill const& fill)
...
         }
     }
-    catch (std::exception const&)
+    catch (std::exception const& ex)
     {
         // Nothing the user can do about this.
+        if (fill.context)
+        {
+            JLOG(fill.context->j.error())
+                << "Exception in " << __func__ << ": " << ex.what();
```
Comment (mtrippled) [inline src/ripple/app/ledger/impl/LedgerToJson.cpp:201]: Same "--func--" question.

File: src/ripple/app/ledger/impl/OpenLedger.cpp [hunk 3]
```diff
@@ -206,9 +206,9 @@ debugTostr(SHAMap const& set)
             auto const tx = std::make_shared<STTx const>(sit);
             ss << debugTxstr(tx) << ", ";
         }
-        catch (std::exception const&)
+        catch (std::exception const& ex)
         {
-            ss << "THRO, ";
+            ss << "THRO:" << ex.what() << ", ";
```
Comment (mtrippled) [inline src/ripple/app/ledger/impl/OpenLedger.cpp:211]: THROW is correct.

File: src/ripple/app/misc/impl/Manifest.cpp [hunk 4]
```diff
@@ -148,8 +148,10 @@ deserializeManifest(Slice s)
 
         return m;
     }
-    catch (std::exception const&)
+    catch (std::exception const& ex)
     {
+        JLOG(journal.error())
+            << "Exception in " << __func__ << ": " << ex.what();
```
Comment (mtrippled) [inline src/ripple/app/misc/impl/Manifest.cpp:154]: Same "--func--" question.

File: src/ripple/app/misc/impl/Manifest.cpp [hunk 5]
```diff
@@ -277,8 +279,10 @@ loadValidatorToken(std::vector<std::string> const& blob)
 
         return std::nullopt;
     }
-    catch (std::exception const&)
+    catch (std::exception const& ex)
     {
+        JLOG(journal.error())
+            << "Exception in " << __func__ << ": " << ex.what();
```
Comment (mtrippled) [inline src/ripple/app/misc/impl/Manifest.cpp:285]: Same "--func--" question.

File: src/ripple/app/misc/impl/ValidatorSite.cpp [hunk 6]
```diff
@@ -632,8 +635,10 @@ ValidatorSite::onTextFetch(
 
             parseJsonResponse(res, siteIdx, lock_sites);
         }
-        catch (std::exception& ex)
+        catch (std::exception const& ex)
         {
+            JLOG(j_.error())
+                << "Exception in " << __func__ << ": " << ex.what();
```
Comment (mtrippled) [inline src/ripple/app/misc/impl/ValidatorSite.cpp:641]: Same "--func--" question.

**Review by mtrippled — CHANGES_REQUESTED** [review]

File: src/ripple/app/ledger/Ledger.cpp [hunk 7]
```diff
@@ -619,8 +620,9 @@ Ledger::setup(Config const& config)
     {
         ret = false;
     }
-    catch (std::exception const&)
+    catch (std::exception const& ex)
     {
+        JLOG(j_.error()) << "Exception in " << __func__ << ": " << ex.what();
```
[the remark this answers is not in the document]
Comment (drlongle) [reply src/ripple/app/ledger/Ledger.cpp:625]: ```__func``` is part of the C++ language since C++11 according to [cppreference.com](https://en.cppreference.com/w/cpp/preprocessor/replace).

Also, it is already used at difference locations in the code base, e.g. [here](https://github.com/XRPLF/rippled/blob/develop/src/ripple/core/impl/JobQueue.cpp#L91).

File: src/ripple/app/ledger/Ledger.cpp [hunk 8]
```diff
@@ -632,8 +634,9 @@ Ledger::setup(Config const& config)
...
```
[the remark this answers is not in the document]
Comment (drlongle) [reply src/ripple/app/ledger/Ledger.cpp:639]: Same answer as above.

File: src/ripple/app/ledger/Ledger.h (hunk 1 above)
Comment (drlongle) [reply src/ripple/app/ledger/Ledger.h:411]: Sure. Fixed.

File: src/ripple/app/ledger/impl/LedgerToJson.cpp (hunk 2 above)
Comment (drlongle) [reply src/ripple/app/ledger/impl/LedgerToJson.cpp:201]: Same answer as above.

File: src/ripple/app/ledger/impl/OpenLedger.cpp (hunk 3 above)
Comment (drlongle) [reply src/ripple/app/ledger/impl/OpenLedger.cpp:211]: Sure. Fixed.

File: src/ripple/app/misc/impl/Manifest.cpp (hunk 4 above)
Comment (drlongle) [reply src/ripple/app/misc/impl/Manifest.cpp:154]: Same answer as above.

File: src/ripple/app/misc/impl/Manifest.cpp (hunk 5 above)
Comment (drlongle) [reply src/ripple/app/misc/impl/Manifest.cpp:285]: Same answer as above.

File: src/ripple/app/misc/impl/ValidatorSite.cpp (hunk 6 above)
Comment (drlongle) [reply src/ripple/app/misc/impl/ValidatorSite.cpp:641]: Same answer as above.

**Review by mtrippled — APPROVED** [review]
+1 LGTM

File: src/ripple/overlay/impl/PeerImp.cpp [hunk 9]
```diff
@@ -3566,7 +3570,7 @@ PeerImp::processLedgerRequest(std::shared_ptr<protocol::TMGetLedger> const& m)
                         << "processLedgerRequest: getNodeFat returns false";
                 }
             }
-            catch (std::exception& e)
+            catch (std::exception const& e)
```
Comment (HowardHinnant) [inline src/ripple/overlay/impl/PeerImp.cpp:3573]: Good catch.

**Review by HowardHinnant — APPROVED** [review]

**Comment by intelliot** [comment]
@drlongle at your convenience, please do the following:
1. resolve the merge conflicts
2. write a proposed commit message (for the entire squashed PR)
3. comment here with that commit message, and confirm that you believe this PR is ready to merge

**Comment by drlongle** [comment]
I have resolved the conflicts and squashed the commits. The PR is ready to merge.

**Comment by intelliot** [comment]
Suggested commit message:
```
Add logging for exceptions: (#4400)

Log exception messages at several locations.

Previously, these were locations where an exception was caught, but the
exception message was not logged. Logging the exception messages can be
useful for analysis or debugging. The additional logging can have a
small negative performance impact.

Fix #3213.
```
@drlongle please confirm this looks good, or suggest an alternative.

**Comment by drlongle** [comment]
@intelliot Looks good. Thanks!
