### PR TITLE
fix "account_nfts" with unassociated marker returning issue

### LINKED ISSUE #4314: "account_nfts" with unassociated marker is returning account_nfts instead of error.
## Issue Description
"account_nfts" with unassociated marker(i.e., marker from another method "account_channels") is not returning error.

## Steps to Reproduce
`{
  "method": "account_nfts",
  "params": [{
    "account": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
    "ledger_index": "validated",
    "limit": 20,
    "marker": "10394D3EA937A85A4482D2071412A33C8582A6EB4C3B7FD59C76012D83AC08C6"
  }]
}`

## Expected Result
Error

## Actual Result
`{
    "result": {
        "account_nfts": [
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0000099B00000000",
                "NFTokenTaxon": 0,
                "nft_serial": 0
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0665C6C80000002D",
                "NFTokenTaxon": 0,
                "nft_serial": 45
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0A85CBBD00000022",
                "NFTokenTaxon": 0,
                "nft_serial": 34
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0EA5D0B200000017",
                "NFTokenTaxon": 0,
                "nft_serial": 23
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B12C5D5A70000000C",
                "NFTokenTaxon": 0,
                "nft_serial": 12
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B16E5DA9C00000001",
                "NFTokenTaxon": 0,
                "nft_serial": 1
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B1D4B97C90000002E",
                "NFTokenTaxon": 0,
                "nft_serial": 46
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B216B9CBE00000023",
                "NFTokenTaxon": 0,
                "nft_serial": 35
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B258BA1B300000018",
                "NFTokenTaxon": 0,
                "nft_serial": 24
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B29ABA6A80000000D",
                "NFTokenTaxon": 0,
                "nft_serial": 13
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B2DCBAB9D00000002",
                "NFTokenTaxon": 0,
                "nft_serial": 2
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B343168CA0000002F",
                "NFTokenTaxon": 0,
                "nft_serial": 47
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B38516DBF00000024",
                "NFTokenTaxon": 0,
                "nft_serial": 36
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B3C7172B400000019",
                "NFTokenTaxon": 0,
                "nft_serial": 25
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B409177A90000000E",
                "NFTokenTaxon": 0,
                "nft_serial": 14
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B44B17C9E00000003",
                "NFTokenTaxon": 0,
                "nft_serial": 3
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B4F373EC000000025",
                "NFTokenTaxon": 0,
                "nft_serial": 37
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B535743B50000001A",
                "NFTokenTaxon": 0,
                "nft_serial": 26
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B577748AA0000000F",
                "NFTokenTaxon": 0,
                "nft_serial": 15
            },
            {
                "Flags": 0,
                "Issuer": "rfALyz8SX9UN444d7iQnpjnWLhtr8Cm2f5",
                "NFTokenID": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B5B974D9F00000004",
                "NFTokenTaxon": 0,
                "nft_serial": 4
            }
        ],
        "ledger_hash": "B61D547D8535A30745330F7B45EA83CA5D9087E27B3E30F726FB1C9FB38F7232",
        "ledger_index": 28634241,
        "limit": 20,
        "marker": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B5B974D9F00000004",
        "status": "success",
        "validated": true
    }
}`

### PR DESCRIPTION
**Pull request by yinyiqian1**
fix #4314 

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Performance (increase or change in throughput and/or latency)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

### CODE REVIEW

**Review by shawnxie999 — COMMENTED** [review]
Good job! left some comments.

also I'm wondering if this should be part of a new API version instead? @intelliot do you know if such API bug changes should introduce a new version or can we just change directly? (edit: nevermind i don't think it needs it since it's not breaking change)

File: src/test/rpc/AccountObjects_test.cpp [hunk 1]
```diff
@@ -1032,13 +1032,134 @@ class AccountObjects_test : public beast::unit_test::suite
...
+
+        unsigned nftsSize = 10;
+        for (unsigned i = 0; i < nftsSize; i++)
+        {
+            env(token::mint(bob, 0));
+        }
+
+        env.close();
+
+        auto createFakeMarker = [](AccountID const& issuer,
```
Comment (shawnxie999) [inline src/test/rpc/AccountObjects_test.cpp:1054]: might be useful to add some comments for what this lambda do and why its defined and where it can be used.

File: src/test/rpc/AccountObjects_test.cpp [hunk 2]
```diff
@@ -1032,13 +1032,134 @@ class AccountObjects_test : public beast::unit_test::suite
...
+            params[jss::account] = bob.human();
+            params[jss::ledger_index] = "validated";
+            auto const resp =
+                env.rpc("json", "account_nfts", to_string(params));
+            auto const& nfts = resp[jss::result][jss::account_nfts];
+            for (auto const& nft : nfts)
+                tokenIDs.push_back(nft["NFTokenID"]);
+        }
+
+        auto compareNFTs = [&](unsigned const limit, unsigned const lastIndex) {
```
Comment (shawnxie999) [inline src/test/rpc/AccountObjects_test.cpp:1093]: comments might be helpful here too

**Comment by intelliot** [comment]
> I'm wondering if this should be part of a new API version instead? @intelliot do you know if such API bug changes should introduce a new version or can we just change directly? (edit: nevermind i don't think it needs it since it's not breaking change)

Right - I see this as a bug fix. However, if we know with certainty that there are API consumers who will be broken by this change, then it would also be ok to put it on api_version 3. But currently, I don't think that is needed.

File: src/test/rpc/AccountObjects_test.cpp [hunk 3]
```diff
@@ -1032,13 +1032,139 @@ class AccountObjects_test : public beast::unit_test::suite
...
+            env(token::mint(bob, 0));
+        }
+
+        env.close();
+
+        // this lambda function is used to create some fake marker using given
+        // taxon and sequence because we want to test some invalid markers later
+        auto createFakeMarker = [](AccountID const& issuer,
+                                   std::string taxonStr,
+                                   std::string tokenSeqStr,
```
Comment (shawnxie999) [inline src/test/rpc/AccountObjects_test.cpp:1058]: why are taxon and seq in std::string instead of uint32?

File: src/test/rpc/AccountObjects_test.cpp [hunk 4]
```diff
@@ -1032,13 +1032,139 @@ class AccountObjects_test : public beast::unit_test::suite
...
+        for (unsigned i = 0; i < nftsSize; i++)
+        {
+            env(token::mint(bob, 0));
+        }
+
+        env.close();
+
+        // this lambda function is used to create some fake marker using given
+        // taxon and sequence because we want to test some invalid markers later
+        auto createFakeMarker = [](AccountID const& issuer,
```
Comment (shawnxie999) [inline src/test/rpc/AccountObjects_test.cpp:1056]: maybe it can be renamed to `createFakeNFTMarker` to make it more clear

File: src/test/rpc/AccountObjects_test.cpp [hunk 5]
```diff
@@ -1032,13 +1032,139 @@ class AccountObjects_test : public beast::unit_test::suite
         BEAST_EXPECT(acct_objs_is_size(acct_objs(gw, jss::hashes), 0));
     }
 
+    void
+    testNFTsMarker()
+    {
+        testcase("NFTsMarker");
```
Comment (shawnxie999) [inline src/test/rpc/AccountObjects_test.cpp:1038]: it might be useful to have some comments in the beginning to describe the what this test is trying to achieve from a high level

File: src/test/rpc/AccountObjects_test.cpp [hunk 6]
```diff
@@ -1032,13 +1032,149 @@ class AccountObjects_test : public beast::unit_test::suite
...
+        // this test tests both situations when providing valid nft marker
+        // and unassociated nft marker.
+        testcase("NFTsMarker");
+
+        using namespace jtx;
+        Env env(*this);
+
+        Account const bob{"bob"};
+        env.fund(XRP(10000), bob);
+
```
Comment (shawnxie999) [inline src/test/rpc/AccountObjects_test.cpp:1049]: it might be better if the lambda definitions are moved up here. right now they're in the middle of test logic

File: src/xrpld/rpc/handlers/AccountObjects.cpp [hunk 7]
```diff
@@ -123,9 +126,18 @@ doAccountNFTs(RPC::JsonContext& context)
                 continue;
 
             if (!pastMarker && maskedNftokenID == maskedMarker &&
-                nftokenID <= marker)
+                nftokenID < marker)
                 continue;
 
+            if (nftokenID == marker)
```
Comment (scottschurr) [inline src/xrpld/rpc/handlers/AccountObjects.cpp:132]: You can make the code slightly more efficient by not checking for equality if the `pastMarker` flag is set.

But once you add that condition you'll see three consecutive `if`s checking `!pastMarker`.  That's probably easier to read and maintain if it's a single condition.  So consider changing the three conditions to this:
```
            if (!pastMarker)
            {
                if (maskedNftokenID < maskedMarker)
                    continue;

                if (maskedNftokenID == maskedMarker && nftokenID < marker)
                    continue;

                if (nftokenID == marker)
                {
                    markerFound = true;
                    continue;
                }
            }
```

**Review by scottschurr — CHANGES_REQUESTED** [review]
Thanks for this pull request.  This looks like a good change.  I left a number of comments for you to consider.  Most of the comments are optional, but I think they are good guidance.  However the implementation of the `createFakeNFTMarker` lambda really needs to get fixed.

In case it's useful, I piled all of the changes I'm suggesting into the top-most commit here: https://github.com/scottschurr/rippled/commits/yinyiqian1-br_fix_nft_page/  You can look at the commit to see what I intended with my suggestions.  You are also welcome to cherry-pick the commit if you decide you want to adopt all of the suggested changes.

I hope that helps.  Feel free to ask further questions about any of the comments that I left.  And thanks again for the pull request.

File: src/test/rpc/AccountObjects_test.cpp [hunk 8]
```diff
@@ -1032,13 +1032,152 @@ class AccountObjects_test : public beast::unit_test::suite
...
+            return uint256::fromVoid(buf.data());
+        };
+
+        // this lambda function is used to check if the account_nfts method
+        // returns the correct token information. lastIndex is used to query the
+        // last marker.
+        auto compareNFTs = [&](unsigned const limit,
+                               unsigned const lastIndex,
+                               unsigned const nftsSize,
+                               const std::vector<Json::Value>& tokenIDs) {
```
[the remark this answers is not in the document]
Comment (yinyiqian1) [reply src/test/rpc/AccountObjects_test.cpp]: Yes. I did not pass in them in my first version. I added them because I was asked to move the lambda function to the beginning of the test case where these values are not defined in the first round review.

File: src/test/rpc/AccountObjects_test.cpp [hunk 9]
```diff
@@ -1032,13 +1032,152 @@ class AccountObjects_test : public beast::unit_test::suite
...
+        using namespace jtx;
+        Env env(*this);
+
+        Account const bob{"bob"};
+        env.fund(XRP(10000), bob);
+
+        // this lambda function is used to create some fake marker using given
+        // taxon and sequence because we want to test some unassociated markers
+        // later
+        auto createFakeNFTMarker = [](AccountID const& issuer,
```
[the remark this answers is not in the document]
Comment (yinyiqian1) [reply src/test/rpc/AccountObjects_test.cpp]: Yes. I agree. I moved the lamda functions up after first round review. Just cherry-picked

File: src/test/rpc/AccountObjects_test.cpp [hunk 10]
```diff
@@ -1032,13 +1032,152 @@ class AccountObjects_test : public beast::unit_test::suite
...
+
+        // test a valid marker which is equal to the third tokenID
+        BEAST_EXPECT(compareNFTs(4, 2, nftsSize, tokenIDs));
+
+        // test a valid marker which is equal to the 8th tokenID
+        BEAST_EXPECT(compareNFTs(4, 7, nftsSize, tokenIDs));
+
+        // test an unassociated marker which does not exist in the NFTokenIDs
+        {
+            Json::Value params;
```
[the remark this answers is not in the document]
Comment (yinyiqian1) [reply src/test/rpc/AccountObjects_test.cpp]: I'm wondering if it is better to put BEAST_EXPECT outside the lambda function. which makes the code as follows:

```C++
      auto testInvalidMarker = [&env, &bob](
                                     auto marker, char const* errorMessage) {
            Json::Value params;
            params[jss::account] = bob.human();
            params[jss::limit] = 4;
            params[jss::ledger_index] = jss::validated;
            params[jss::marker] = marker;
            Json::Value const resp =
                env.rpc("json", "account_nfts", to_string(params));
            return resp[jss::result][jss::error_message] == errorMessage;
        };

        // test an invalid marker that is not a string
        BEAST_EXPECT(testInvalidMarker(17, "Invalid field \'marker\', not string."));

        // test an invalid marker that has a non-hex character
        BEAST_EXPECT(testInvalidMarker(
            "00000000F51DFC2A09D62CBBA1DFBDD4691DAC96AD98B900000000000000000G",
            "Invalid field \'marker\'."));

        // test an unassociated marker which does not exist in the NFTokenIDs
        BEAST_EXPECT(testInvalidMarker(
            createFakeNFTMarker(bob.id(), 0x000000000, 0x00000000),
            "Invalid field \'marker\'."));

        // test an unassociated marker which exceeds the maximum value of the
        // existing NFTokenID
        BEAST_EXPECT(testInvalidMarker(
            createFakeNFTMarker(bob.id(), 0xFFFFFFFF, 0xFFFFFFFF),
            "Invalid field \'marker\'."));
```

removed `this` in testInvalidMarker's capture because it's not used.

Moving BEAST_EXPECT out is to better locate the error if some check fails. Otherwise, we can't tell where's the error directly if the BEAST_EXPECT check fails in the lambda function

[the remark this answers is not in the document]
Comment (scottschurr) [reply src/test/rpc/AccountObjects_test.cpp]: Yes, I agree.  This looks better than what I suggested.  Moving the `BEAST_EXPECT` out gives more understandable errors messages if the test fails.  Thanks!

**Review by shawnxie999 — APPROVED** [review]
LGTM
