### PR TITLE
API does not accept seed or public key for account

### LINKED ISSUE #3329: account_objects CLI usage statement is wrong (Version: 1.5.0)
## Issue Description
(Discovered while documenting #3196.) The usage statement for the `account_objects` method is wrong. [[Source code]](https://github.com/ripple/rippled/blob/f00f263852c472938bf8e993e26c7f96f435935c/src/ripple/app/main/Main.cpp#L135)

The account_objects method does not support the `strict` parameter, but the commandline implies it does.

## Steps to Reproduce

Start rippled in stand-alone mode, then run this command:

```sh
rippled account_objects masterpassphrase current strict
```

## Expected Result
The result should be an `actMalformed` error, similar to what you get if you do `account_info` with the same arguments.

```json
{
   "result" : {
      "error" : "actMalformed",
      "error_code" : 35,
      "error_message" : "Account malformed.",
      "request" : {
         "account" : "masterpassphrase",
         "api_version" : 1,
         "command" : "account_objects",
         "strict" : 1
      },
      "status" : "error"
   }
}
```

The "easy" fix is to correct the usage statement not to mention the `strict` parameter, which is not supported in any interface for `account_objects`. But my preferred fix is to **add `strict` support to `account_objects`** for consistency with other account_* methods.

## Actual Result
The server returns a successful response for the genesis account:

```json
{
   "result" : {
      "account" : "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
      "account_objects" : [],
      "ledger_current_index" : 3,
      "status" : "success",
      "validated" : false
   }
}
```

### PR DESCRIPTION
**Pull request by drlongle**
## High Level Overview of Change

This PR resolves #3329, #3330 and #4337. Currently, `seeds` and `public keys` can be used in place of ```accounts``` at several locations in the API. This increases the API's complexity because the API needs to guess whether the input is a seed, a public key or an address. This PR prevents the API from accepting a seed or a public key as account ID. Since the API does not interpret ```account``` as ```seed```, the option ```strict``` in several API methods is no longer needed and is removed.

### Context of Change

Documentation needs to be updated.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [x] Documentation Updates
- [ ] Release

### CODE REVIEW

File: src/ripple/rpc/handlers/AccountChannels.cpp [hunk 1]
```diff
@@ -76,25 +76,29 @@ doAccountChannels(RPC::JsonContext& context)
...
+    if (!ledger->exists(keylet::account(*accountID)))
         return rpcError(rpcACT_NOT_FOUND);
 
     std::string strDst;
     if (params.isMember(jss::destination_account))
         strDst = params[jss::destination_account].asString();
     auto hasDst = !strDst.empty();
 
-    AccountID raDstAccount;
+    std::optional<AccountID> raDstAccount{AccountID()};
```
Comment (justinr1234) [inline src/ripple/rpc/handlers/AccountChannels.cpp:94]: Can you explain this line to me and why it was changed?

File: src/ripple/rpc/handlers/AccountLines.cpp [hunk 2]
```diff
@@ -96,31 +96,29 @@ doAccountLines(RPC::JsonContext& context)
...
 
-    std::string strIdent(params[jss::account].asString());
-    AccountID accountID;
-
-    if (auto jv = RPC::accountFromString(accountID, strIdent))
+    std::string const strIdent(params[jss::account].asString());
+    auto const accountID = parseBase58<AccountID>(strIdent);
+    if (!accountID)
     {
-        for (auto it = jv.begin(); it != jv.end(); ++it)
```
Comment (justinr1234) [inline src/ripple/rpc/handlers/AccountLines.cpp:104]: What did this old code do and why is it removed?

File: src/test/app/TxQ_test.cpp [hunk 3]
```diff
@@ -3097,11 +3097,13 @@ class TxQ1_test : public beast::unit_test::suite
         env.fund(XRP(1000000), alice);
         env.close();
 
+        auto const aliceAccountIDStr = toBase58(alice.id());
         auto const withQueue =
-            R"({ "account": ")" + alice.human() + R"(", "queue": true })";
```
Comment (justinr1234) [inline src/test/app/TxQ_test.cpp:3101]: What does removed `human()` do to the return value? Is it equivalent?

Comment (drlongle) [reply src/test/app/TxQ_test.cpp]: [Account::human()](https://github.com/XRPLF/rippled/blob/develop/src/test/jtx/Account.h#L112) returns the human readable public key. [Account::id()](https://github.com/XRPLF/rippled/blob/develop/src/test/jtx/Account.h#L106) returns the uint160 hash of the public key. Those changes are actually unnecessary. I revert them.

File: src/ripple/rpc/handlers/AccountChannels.cpp (hunk 1 above)
Comment (drlongle) [reply src/ripple/rpc/handlers/AccountChannels.cpp:94]: The old code calls [RPC::accountFromString()](https://github.com/XRPLF/rippled/blob/develop/src/ripple/rpc/impl/RPCHelpers.cpp#L85) with  `bStrict = false` (default value). This function attempts different ways to parse the input string (it checks whether the input is a public key, an account ID or a seed). If one of these attempts works, the function fills the content of the pointer of type `AccountID` and returns an empty Json object. Otherwise, the function returns a Json object that contains an error code and an error message.

Since we don't accept seed as a way to look up an account, I call the function [parseBase58()](https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/impl/AccountID.cpp#L114) instead. This function has a different syntax. It returns an `std::optional<AccountID>` object that only contains an `AccountID` when the input string is actually an account ID (a valid hash).

File: src/ripple/rpc/handlers/AccountLines.cpp (hunk 2 above)
Comment (drlongle) [reply src/ripple/rpc/handlers/AccountLines.cpp:104]: The function [RPC::accountFromString()](https://github.com/XRPLF/rippled/blob/develop/src/ripple/rpc/impl/RPCHelpers.cpp#L85) attempts different ways to parse the input string (it checks whether the input is a public key, an account ID or a seed). If  all attempts fail, the function returns a Json object that contains an error code and an error message. The `for` loop traverses the return Json object and add all its fields (error code and error message) to the `Json` result object.

The new code calls the function [inject_error](https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/ErrorCodes.h#L212) and achieves the same effect.

**Review by seelabs — COMMENTED** [review]
This looks good, thanks. I'm not sure I would have removed the public_key methods. That isn't a security concern, but I also understand the motivation - I don't object too strongly. I left a few suggestions. Nice job on this.

File: src/ripple/rpc/handlers/AccountLines.cpp [hunk 4]
```diff
@@ -96,31 +96,29 @@ doAccountLines(RPC::JsonContext& context)
...
+    if (!ledger->exists(keylet::account(*accountID)))
         return rpcError(rpcACT_NOT_FOUND);
 
     std::string strPeer;
     if (params.isMember(jss::peer))
         strPeer = params[jss::peer].asString();
     auto hasPeer = !strPeer.empty();
 
-    AccountID raPeerAccount;
+    std::optional<AccountID> raPeerAccount{AccountID()};
```
[the remark this answers is not in the document]
Comment (drlongle) [reply src/ripple/rpc/handlers/AccountLines.cpp]: Thanks. Fixed.

File: src/ripple/rpc/handlers/AccountOffers.cpp [hunk 5]
```diff
@@ -137,11 +134,11 @@ doAccountOffers(RPC::JsonContext& context)
     std::uint64_t nextHint = 0;
     if (!forEachItemAfter(
             *ledger,
-            accountID,
+            *accountID,
             startAfter,
             startHint,
             limit + 1,
-            [&offers, &count, &marker, &limit, &nextHint, &accountID](
+            [&offers, &count, &marker, &limit, &nextHint, accountID](
```
[the remark this answers is not in the document]
Comment (drlongle) [reply src/ripple/rpc/handlers/AccountOffers.cpp]: You are right. Fixed.

**Review by seelabs — APPROVED** [review]
:+1: nice job on this.

**Comment by intelliot** [comment]
@drlongle it isn't necessary to rebase and force-push (though you can if you prefer - it's just a little trickier for reviewers to follow the changes). Using merge commits is fine if we're going to squash this PR when merging it.

**Review by justinr1234 — APPROVED** [review]

**Comment by intelliot** [comment]
(I believe drlongle still needs to respond to gregtatcam's suggestions)

File: src/ripple/rpc/handlers/AccountCurrenciesHandler.cpp [hunk 6]
```diff
@@ -46,19 +46,19 @@ doAccountCurrencies(RPC::JsonContext& context)
...
                                       : params[jss::ident].asString());
 
-    bool const bStrict =
-        params.isMember(jss::strict) && params[jss::strict].asBool();
-
     // Get info on account.
-    AccountID accountID;  // out param
-    if (auto jvAccepted = RPC::accountFromString(accountID, strIdent, bStrict))
-        return jvAccepted;
+    auto const accountID = parseBase58<AccountID>(strIdent);
```
Comment (gregtatcam) [inline src/ripple/rpc/handlers/AccountCurrenciesHandler.cpp:50]: `AccountID` is not really optional. Please consider the updated suggested in `AccountChannels.cpp` comment. I will not repeat this comment for other files. All changed files under `rpc/handlers` have a similar code block: AccountInfo.cpp, AccountLines.cpp, AccountObjects.cpp, AccountOffers.cpp, DepositAuthorized.cpp, GatewayBalances.cpp, NoRipplecheck.cpp, OwnerInfo.cpp.

File: src/ripple/rpc/handlers/AccountChannels.cpp [hunk 7]
```diff
@@ -179,9 +177,9 @@ doAccountChannels(RPC::JsonContext& context)
                 }
 
                 if (count <= limit && sleCur->getType() == ltPAYCHAN &&
-                    (*sleCur)[sfAccount] == accountID &&
-                    (!visitData.hasDst ||
-                     visitData.raDstAccount == (*sleCur)[sfDestination]))
+                    (*sleCur)[sfAccount] == *accountID &&
+                    (!visitData.raDstAccount ||
+                     *visitData.raDstAccount == (*sleCur)[sfDestination]))
```
[the remark this answers is not in the document]
Comment (gregtatcam) [reply src/ripple/rpc/handlers/AccountChannels.cpp:182]: You are right. I'm taking back this suggestion.

File: src/ripple/rpc/handlers/AccountLines.cpp [hunk 8]
```diff
@@ -227,8 +218,8 @@ doAccountLines(RPC::JsonContext& context)
                             RPCTrustLine::makeItem(visitData.accountID, sleCur);
 
                         if (line &&
-                            (!visitData.hasPeer ||
-                             visitData.raPeerAccount ==
+                            (!visitData.raPeerAccount ||
+                             *visitData.raPeerAccount ==
```
[the remark this answers is not in the document]
Comment (gregtatcam) [reply src/ripple/rpc/handlers/AccountLines.cpp:222]: You are right. I'm taking back this suggestion.

File: src/ripple/rpc/handlers/GatewayBalances.cpp [hunk 9]
```diff
@@ -90,17 +86,7 @@ doGatewayBalances(RPC::JsonContext& context)
...
-                if (pk)
-                {
-                    hotWallets.insert(calcAccountID(*pk));
-                    return true;
-                }
-
-                auto const id = parseBase58<AccountID>(j.asString());
-
-                if (id)
+                if (auto const id = parseBase58<AccountID>(j.asString()); id)
```
[the remark this answers is not in the document]
Comment (gregtatcam) [reply src/ripple/rpc/handlers/GatewayBalances.cpp:89]: The original code is:
```
auto const id = parseBase58<AccountID>(j.asString());

                if (id)
                {
                    hotWallets.insert(*id);
                    return true;
                }
```
In this case it does need to be checked. In case of `if` with initializer it's checked if there is no other condition.

File: src/ripple/rpc/handlers/AccountCurrenciesHandler.cpp (hunk 6 above)
Comment (drlongle) [reply src/ripple/rpc/handlers/AccountCurrenciesHandler.cpp]: I have applied your suggested changes across the board. Let me know if you find any further issues.

**Review by gregtatcam — APPROVED** [review]
👍 LGTM
