### PR TITLE
Proposed 1.10.0-b1

### LINKED ISSUE #4250: Fix broken Doxygen link in README
After porting the codebase to XRPLF Github repository, the link to Doxygen documentation is broken. Previously, it pointed to `https://rippled.github.io/rippled/`. It needs to be reconfigured for `https://xrplf.github.io/rippled/` 

I'm referring to the README file at the root of the repository - `README.md`

### PR DESCRIPTION
**Pull request by nbougalis**
If merged this PR will:

- close #4105 (with fix for return value added!)
- close #4174
- close #4181 
- close #4195 
- close #4237 
- close #4240 
- close #4245 
- close #4249 
- close #4250 
- close #4251
- close #4254 
- close #4256 
- close #4261

### CODE REVIEW

File: src/ripple/protocol/impl/AccountID.cpp [hunk 1]
```diff
@@ -17,17 +17,95 @@
...
+
+        auto ret =
+            encodeBase58Token(TokenType::AccountID, id.data(), id.size());
+
+        assert(ret.size() <= 38);
+
+        {
+            std::lock_guard lock(sl);
+            cache_[index].id = id;
+            std::strcpy(cache_[index].encoding, ret.c_str());
```
Comment (ximinez) [inline src/ripple/protocol/impl/AccountID.cpp:85]: I know there's an `assert` a couple of lines up, but `strcpy` always raises my hackles. Would it hurt to use `strncpy`?

**Review by ximinez — APPROVED** [review]
Tested in Windows with VS2019.

File: src/ripple/app/main/NodeIdentity.cpp [hunk 2]
```diff
@@ -20,34 +20,49 @@
...
         auto secretKey = generateSecretKey(KeyType::secp256k1, *seed);
         auto publicKey = derivePublicKey(KeyType::secp256k1, secretKey);
 
         return {publicKey, secretKey};
     }
 
     auto db = app.getWalletDB().checkoutDb();
+
+    if (cmdline.count("newnodeid") != 0)
+        clearNodeIdentity(*db);
```
[the remark this answers is not in the document]
Comment (nbougalis) [reply src/ripple/app/main/NodeIdentity.cpp:64]: I don't _think_ there's a problem with doing that. `--newnodeid` clears any node identities stored in the database, but it may be worth notifying. We ought to fix this separately, IMO.

File: src/ripple/protocol/impl/AccountID.cpp (hunk 1 above)
Comment (nbougalis) [reply src/ripple/protocol/impl/AccountID.cpp:85]: It wouldn't hurt. I'll make a follow-up fix for this, if you don't mind merging this as is.
