### PR TITLE
fix: crash when trace-logging in tests

### LINKED ISSUE #5388: Double free of object malloc error when running `beast::severities::kTrace`
## Issue Description

```
rippled(38872,0x16d2e7000) malloc: Double free of object 0x12f905ff0
rippled(38872,0x16d2e7000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ./rippled -u ripple.app.Batch

```

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

This PR fixes a crash in tests when the test `Env is run at trace/debug log level.

This issue only affects tests, and only if logging at trace/debug level, so really only relevant during rippled development, and does not affect production servers.

Note: I think the logs run a bit slower with this fix, due to the lock, but IMO that's not a big deal since this is only relevant for development

h/t @sublimator for the fix in the issue

### Context of Change

Fixes #5388 

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### API Impact

N/A

## Test Plan

Worked locally.

Repro instructions are in the issue.

### CODE REVIEW

File: src/test/unit_test/SuiteJournal.h [hunk 1]
```diff
@@ -94,6 +94,8 @@ SuiteJournalSink::writeAlways(
         return "FTL:";
     }();
 
+    static std::mutex log_mutex_;
```
Comment (vlntb) [inline src/test/unit_test/SuiteJournal.h:97]:
```suggestion
    static std::mutex log_mutex;
```

**Review by vlntb — CHANGES_REQUESTED** [review]
LGTM. One little nit.

**Review by vlntb — APPROVED** [review]
